=== JeffersonTolentino/Festival-Application/web/WEB-INF/BandMemberSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>




<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="bandlist">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="band" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="bandname"/>
              <xs:element type="xs:string" name="genre"/>
              <xs:element type="xs:string" name="bandinfo"/>
              <xs:element name="bandmembers">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="member" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="name"/>
                          <xs:element type="xs:string" name="dob"/>
                          <xs:element type="xs:string" name="origin"/>
                          <xs:element type="xs:string" name="instrument"/>
                          <xs:element type="xs:string" name="details"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="id" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JeffersonTolentino/Festival-Application/build/web/WEB-INF/Bands.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="Bands.xsl" type="text/xsl"?>
<?xml-stylesheet href="BandMember.xsl" type="text/xsl"?>

<bandlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:noNamespaceSchemaLocation='BandMemberSchema.xsd'>



	

	<band id ="m3">

	<name>Green Day</name>
	<genre> Punk rock </genre>
	<bandinfo> Green Day is an American punk rock band formed in 1987 by lead vocalist Billie Joe Armstrong and bassist and backing vocalist Mike Dirnt. For much of their career the band has been a trio with drummer TrÃ© Cool and in 2012 Jason White became a full time member after playing as backup vocals and guitar for 13 years. The band was originally named Sweet Children and was part of the punk scene at the DIY 924 Gilman Street club in Barkley California. </bandinfo> 
	
		<bandmembers>
	
			<member id="1">
                
				<name>Billie Joe Armstrong</name>
			
				<dob> 17/02/1972 </dob>
			
				<origin> Rodeo, California, US</origin>
			
				<instrument>Vocals &amp; Guitar </instrument>
			
				<details> Billie Joe Armstrong is an American singer, songwriter, guitarist &amp; multi-instrumentalist from Oakland, California. Armstrong is the co-founder and lead vocalist/guitarist of the punk rock band Green Day along with Mike Dirnt.  </details>
                                
                                <image>billiejoe.jpg</image>
	
			</member>
			
			
			
			<member id="2">
		
				<name>Michael Ryan Pritchard(Mike Dirnt)</name>
			
				<dob> 04/05/1972</dob>
			
				<origin> Berkeley, California, US</origin>
			
				<instrument> Bass </instrument>
			
				<details> Mike Dirnt is an American musician best know as the bassist and co-founder of the punk rock band Green Day. His stage name was originally a nickname from his friends at grade school, as he would constantly play &apos;air bass&apos; and make a &apos;dirnt, dirnt, dirnt&apos; noise while pretending to pluck the strings.  </details>
	
                                <image>michaelryan.jpg</image>
			</member>
			
			<member id="3">
		
				<name>Frank Edwin Wright III (Tre Cool)</name>
			
				<dob>09/12/1972</dob>
			
				<origin>Willits, California, US</origin>
			
				<instrument>Drums</instrument>
			
				<details>Frank Edwin Wright III best known as Tre Cool is the drummer of Green Day. He replaced the group&apos;s former drummer John Kiffmeyer in 1990.  </details>
	
                                 <image>FrankEd.jpg</image>
			</member>
			
			<member id="4">
		
				<name>Jason White</name>
			
				<dob> 11/11/1973</dob>
			
				<origin> North Little Rock, Arkansas, US </origin>
			
				<instrument> Guitar </instrument>
			
				<details> Jason White has been turing with the band since 1999 and on 2012 he was officially part of the band. Now he is the lead guitarist of the Punk Rock band Green Day. He is also the guitarist and vocalist for the Californian punk band Pinhead Gunpowder, and co-founder of Adeline Records alongside Billie Joe Armstrong. </details>
                                 
                                <image>Jasonwhite.jpg</image>
			</member>

		</bandmembers>
	
	</band>
	
	
	
	<band id ="met1">

	<name>KORN</name>
	<genre>  Nu Metal </genre>
	<bandinfo> Korn is an American nu metal band from Bakerfield, California formed in 1993. The metal band has 5 members:  Jonathan Davis (vocals, bagpipes), James "Munky" Shaffer (guitar), Brian "Head" Welch (guitar, backing vocals), and Reginald "Fieldy" Arvizu (bass), with the addition of Ray Luzier  as the drummer. The band also released a dubstep album featuring Sxrillex</bandinfo> 

	
		<bandmembers>

			<member id="1">
		
				<name>Jonathan Davis</name>
			
				<dob> 18/01/1971 </dob>
			
				<origin> Bakersfield, California  </origin>
			
				<instrument> Vocals &amp; bagpipes</instrument>
			
				<details> Jonathan Howsmon Davis is the Vocalist of the American Nu Metal. Jonathan is also known as JD &amp; JDevil.</details>
	
                                <image>jondavis.jpeg</image>
			</member>
			
			
			
			<member id="2">
		
				<name>James Christian Shaffer</name>
			
				<dob> 06/06/1970 </dob>
			
				<origin> Hollywood, California, US</origin>
			
				<instrument> Guitar </instrument>
			
				<details> James Christian Shaffer also known as Munky is the guitarist and co-founder of the nu metal band Korn. His nickname is a reference to his feet that resembles a monkey%apos;s hands when spread.  </details>
				
                                <image>jamesc.jpg</image>
			</member>
			
			<member id="3">
		
				<name>Brian Phillip Welch</name>
			
				<dob> 19/06/1970 </dob>
			
				<origin> Hollywood, California, US</origin>
			
				<instrument> Guitar </instrument>
			
				<details> Brian Phillip Welch  better known as Head is one of guitarist and co-founder of the nu metal band Korn. He helped to develop the distinctive sound of the Nu metal band Korn.  He left the band in 2005 when he became a born again Christian and on May 2, 2013 he officially rejoined the band. </details>
				
                                <image>brianphil.png</image>
			</member>
			
			<member id="4">
		
				<name>Reginald Quincy Arvizu</name>
			
				<dob> 02/11/1969</dob>
			
				<origin> Los Angeles County, California, US </origin>
			
				<instrument> Bass </instrument>
			
				<details>  Reginald Quincy "Fieldy" Arvizu is an American musician. He is best known as the bassist for the nu metal band Korn, and guitarist for the hard rock band StillWell. </details>
				
                                <image>Regi.jpg</image>
			</member>
			
			<member id="5">
		
				<name>Ray Luzier</name>
			
				<dob> 14/06/1970 </dob>
			
				<origin> Pittsburgh, Pennsylvania, US</origin>
			
				<instrument> Drums </instrument>
			
				<details> Ray Luzier  is an American drummer. He is the drummer of the nu metal band Korn, becoming a full-time member of the band in April 2009.</details>
				
                                <image>raylu.jpg</image>
			</member>

		</bandmembers>
	
	</band>
	
	<band id ="a2">

	<name>Asian Kung-Fu Generation</name>
	<genre> Alternative rock </genre>
	<bandinfo> Asian Kung-Fu Generation  is a Japanese alternative rock band formed in Yokohama, Japan, in 1996.  The band's musical style is influenced by seminal Western punk and alternative rock acts in conjunction with their own local Japanese indie rock background. </bandinfo>
	
		<bandmembers>
	
			<member id="1">
		
				<name>Masafumi Gotoh</name>
			
				<dob> 02/12/1976 </dob>
			
				<origin>  Shimada, Japan</origin>
			
				<instrument> Vocals &amp; Guitar </instrument>
			
				<details> Masafumi Gotoh is the lead vocalist, main songwriter and rhythm guitarist of the Japanese rock band Asian Kung-Fu Generation. He met with fellow band members Kensuke Kita and Takahiro Yamada while attending a music club of Kanto Gakuin University. The three formed Asian Kung-Fu Generation in 1996. Gotoh is the main songwriter of the band but he also has the tendency to share song writing with other band members. </details>
	
                                <image>masafumi.jpg</image>
			</member>
			
			
			
			<member id="2">
		
				<name>Kensuke Kita</name>
			
				<dob> 24/01/1977 </dob>
			
				<origin> Tokyo, Japan </origin>
			
				<instrument> Guitar </instrument>
			
				<details> Kensuke Kita is the lead guitarist and backing singer of the Japanese rock band Asian Kung-Fu Generation. Kensuke met fellow band members Masafumi GotÅ� and Takahiro Yamada while attending a music club of Kanto Gakuin University. The three formed Asian Kung-Fu Generation in 1996. He is primarily the lead guitarist of the band.</details>
	
                                <image>Kensuke.jpg</image>
			</member>
			
			<member id="3">
		
				<name>Takahiro Yamada</name>
			
				<dob> 19/08/1977 </dob>
			
				<origin> Fujinomiya, Japan </origin>
			
				<instrument> Bass </instrument>
			
				<details> Takahiro Yamada  is the bass player and backing singer of the Japanese rock band Asian Kung-Fu Generation. Yamada met fellow band members Masafumi GotÅ� and Kensuke Kita while attending a music club of Kanto Gakuin University. The three formed Asian Kung-Fu Generation in 1996. Yamada also provided lyrics for certain songs.  </details>
	
                                <image>Takahiro.jpg</image>
			</member>
			
			<member id="4">
		
				<name>Kiyoshi Ijichi</name>
			
				<dob> 25/09/1977 </dob>
			
				<origin> Tokyo, Japan </origin>
			
				<instrument> Drummer </instrument>
			
				<details> Kiyoshi Ijichi  is the drummer of the Japanese rock band Asian Kung-Fu Generation. Ijichi credits the origin of his drumming ability to playing in marching bands in junior high. He meet up with the other members of the band while attending at kondo gakuin university in 1996 but unlike the other members he had prior band experience from another college.</details>
	
                                <image>Kiyosh.jpg</image>
			</member>

		</bandmembers>
	
	</band>
	
	<!-- Nathans Bands -->
	<band id ="m1">

	<name>Tame Impala</name>
	<genre> Psychedelic Rock </genre>
	<bandinfo>  Tame Impala are an Australian Psychedelic Rock Band formed in 2007 by Kevin Parker. Parker maninly records the music by himself in the studio and brings the band to tour with him. </bandinfo> 
	
		<bandmembers>
	
			<member id="1">
		
				<name>Kevin Parker</name>
			
				<dob> 20/01/1986 </dob>
			
				<origin> Perth, Western Australia, Australia</origin>
			
				<instrument>Vocals &amp; Guitar </instrument>
			
				<details> Kevin Parker is the founder and main creative drive of Tame Impala and he writes and records the majority of the music. </details>
	
                                <image>kevinparker.jpg</image>
			</member>
			
			
			
			<member id="2">
		
				<name>Jay Watson</name>
			
				<dob> 27/05/1990</dob>
			
				<origin> Fremantle, Western Australia, Australia</origin>
			
				<instrument> Keyboard </instrument>
